### ISSUE TITLE
Missing error handling?

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#124]
TRACE 2018-12-07 22:31:16.279 [Thread-37] net.pms.io.WindowsNamedPipe 
java.io.InterruptedIOException: null
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:276)
	at java.io.PipedInputStream.receive(PipedInputStream.java:232)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at java.io.OutputStream.write(OutputStream.java:75)
	at net.pms.io.WindowsNamedPipe.run(WindowsNamedPipe.java:276)

**Comment by Nadahar** [comment]
It looks very much "handled" to me. It is caught and and logged, what more can you do about an interrupt? What it means is that something externally interrupted it - told it to stop waiting. The clue to "solving" this is to find out what is telling it to stop what it's doing and why. Sadly, the exception doesn't contain this information.

**Comment by Nadahar** [comment]
The problem is that there's no information available in the exception itself. It might be possible to make a better logic using information not in the exception, but then we'd need to study how all this works and why it ends up being interrupted.

**Comment by Sami32** [comment]
It seem that after some time without input this error is showed.
Nothing to worry, just not informative, useful logging in this case.
