### ISSUE TITLE
DCRaw failure on ARI files

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#14]
I don't if it's worst mention it, but DCRaw fail on ARI. Nothing to do except perhaps eventually defer it to FFmpeg, in the case it support it, i dinst tried yet.
https://we.tl/ZFFBG2ewrb

```logtalk
DEBUG 2017-08-13 20:59:58.109 [Library Scanner] Starting "C:\Program Files\Universal Media Server\win32\dcrawMS.exe" -e -c -M -w "F:\!MEDIA_TEST_FILES\UMS Video Testing Suite (20150121)\TESTS\A006C021_150902_R0D0.0044458.ari"
DEBUG 2017-08-13 20:59:58.125 [dcrawMS.exe-4-2] F:\!MEDIA_TEST_FILES\UMS Video Testing Suite (20150121)\TESTS\A006C021_150902_R0D0.0044458.ari has no thumbnail.
INFO  2017-08-13 20:59:58.140 [Library Scanner] Process "C:\Program Files\Universal Media Server\win32\dcrawMS.exe" has a return code of 1! Maybe an error occurred... check the log file
DEBUG 2017-08-13 20:59:58.140 [Library Scanner] Starting ""C:\Program Files\Universal Media Server\win32\dcrawMS.exe"" -h -c -M -w ""F:\!MEDIA_TEST_FILES\UMS Video Testing Suite (20150121)\TESTS\A006C021_150902_R0D0.0044458.ari""
```

**Comment by Nadahar** [comment]
I took a quick look at the ARRI format, and it's as proprietary as they get. They only give the specification to "partners" that are big players in the professional scene. Here's the software that can read ARRI files: http://www.arri.com/camera/alexa/workflow/working_with_arriraw/arriraw/processing_tools/

It's not just a custom format, the file contains the raw sensor data - so you'd probably have to know quite a lot about the sensor itself to be able to convert it into an image. I don't think anyone would or should expect ARRIRaw files to be playable for anything except professional, high end image/video processing software.

A better solution would probably to remove the extension from the "supported" extensions. I see that it's currently listed under ```RAW```. It was added in 90454ecd3943e0c9ea429f60de730b98c732cd08/[```bef3973```](https://github.com/ps3mediaserver/ps3mediaserver/commit/bef397325e6f88f1029bb1a2eb6daaa619f97f14), but the commit doesn't exactly give much explanation. My guess is that simply a lot of RAW extensions was added without testing if they actually could be handled.

**Comment by Sami32** [comment]
Sorry, y bad, i was testing a PR while i saw it and posted in a hurry, an other not related images issues, but didn't tried. I just tested briefly it now.
It's not bad, as FFmpeg is able to handle it and the thumbnail is displayed.

So, it can stay as it is, or an exception for DCRAw could be added ?

**Comment by Nadahar** [comment]
@Sami32 There's no need to make an exception for DCRaw. Still, the image won't display - only the thumbnail, unless we implement FFmpeg "transcoding" for images too.

**Comment by Sami32** [comment]
Yes. But i think that many many others things should have a highter priority on this very rare case ;-)

**Comment by Nadahar** [comment]
@Sami32 Absolutely, my point was only that it's not really supported, so the best thing to do would probably be to remove the extension for the "supported" extensions.

**Comment by Sami32** [comment]
I'm not sure, users can always see their thumbnails and wait for an FFmpeg transcoding implementation ?

**Comment by Nadahar** [comment]
I doubt anyone will ever try to share an ARI image, but if they do I don't think having a working thumbnail will make them very happy. It will seem like a bug rather than simply not being supported.
