### ISSUE TITLE
Interesting documentation related to macOS build

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#15]
I considered that it deserved it own "issue", and share my documentations compilation here, in case i forget them somewhere :wink: 

https://github.com/andreyvit/create-dmg
https://github.com/LinusU/node-appdmg
https://asmaloney.com/2013/07/howto/packaging-a-mac-os-x-application-using-a-dmg/
https://gist.github.com/jadeatucker/5382343
https://github.com/MagerValp/AutoDMG
http://www.rkuntz.org/pmwiki.php?n=Code.AntDiskImage
http://centerkey.com/mac/java/

http://www.elstensoftware.com/blog/2013/04/17/scripting-dmg-build-osx-linux/

https://dragly.org/2012/01/13/deploy-qt-applications-for-mac-os-x/

http://www.avoiderrors.net/create-dmg-file-macos/

http://www.scala-sbt.org/sbt-native-packager/formats/jdkpackager.html
http://planet.jboss.org/post/packaging_java_applications_for_mac_os_javapackager
http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html
http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/packagingAppsForMac.html

- DMG build from NetBeans IDE on macOS:
https://dzone.com/articles/nb-mac-dragdrop-install

And of course the last i found...as said the proverb ;-)
- **Signed DMG from Eclipse:** :smile: 
***** https://bugs.eclipse.org/bugs/show_bug.cgi?id=106350 ***** :-D
https://hudson.eclipse.org/packaging/job/oxygen.epp-tycho-build/
http://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/commit/?id=e6f02e6816fbe247d62d59847965d052dae2b06e
https://www.eclipse.org/cbi/maven-plugins/documentation/1.1.3/eclipse-macsigner-plugin/plugin-info.html

Note to myself for later deeper check: (to see if building under Windows will be possible)
https://github.com/Jorl17/jar2app
https://github.com/libgdx/packr

**EDIT**: @Optimusprimeums, who maintained and have done macOS builds,  and [@sebos](https://fi.linkedin.com/in/anttiniiles/de) was the ones that worked on it when Mac OS build has been upgraded to Java 7. 
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=868&p=5865&hilit=build+Mac+os#p5976
http://www.universalmediaserver.com/forum/viewtopic.php?f=11&t=612

**Comment by Nadahar** [comment]
@Sami32 AFAIK Java 8 can make DMGs natively..? I'm not so worried about automating that as you know, but I think it'll be easy to do once Java 7 is ditched.

**Comment by Sami32** [comment]
I hope you don't mind that i posted it here ?

Many others points are interesting to me, nothing to do with Java 8, as we can do with Java 7 as well.
A "simple" script for all plateform, signing...
As i know as i'm forgetful i prefered post here, for me, but also to share it to the OpenSource communauty, as search is time consuming...

**Comment by Nadahar** [comment]
It's fine that you're posting it, and I think the method you suggested in your PR could be made to work if the plugin is modified - I'm simply saying that I don't see this as a priority, especially since I think Java 8 will make it much easier.

**Comment by Sami32** [comment]
Not a priority at all, but as i was curious and searched on that, i posted my findings here.
Java 8 will not sign your DMG if you don't have paid a signature...

**Comment by Nadahar** [comment]
@Sami32 I don't plan on signing anything anyway, we could offer MD5 and SHA1 checksums in the future for those that want to verify the file.

**Comment by Sami32** [comment]
I see, you didn't read the link. Anyway, it was more for my use in the coming months.

**Comment by Nadahar** [comment]
@Sami32 Which link? You posted 20 links, I obviously didn't read them.

**Comment by Sami32** [comment]
We was talking about signing, the the one with stars, but it's look too difficult to sign the macOS application, so avoid you looking at it :tongue:
