### ISSUE TITLE
Wrong DIDL-Lite bitrate and size informations giving issues while transcoding

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#16]
- I just discovered the bitrate issue while searching why videos with very high bitrate was not playing fine while the transcoding was OK.

Example:
`DEBUG 2017-08-21 01:23:32.660 [HTTPv2 Request Worker 2] Starting transcode/remux of Lossless_FFv1 Test.avi with media info: Container: AVI, Size: 371995296, Video Bitrate: 422721920, Video Tracks: 1, Video Codec: rgb, Duration: 0:00:07.000, Video Resolution: 1024 x 688, Frame Rate: 25.000, DLNAThumbnail: [Format = JPEG, Resolution = 268×180, Size = 33984, DLNA Profile = JPEG_RES_268_180], Mime Type: video/avi`

`<Result>&lt;DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:sec="http://www.sec.co.kr/" xmlns:pv="http://www.pv.com/pvns/"&gt;&lt;item id="86" parentID="53" restricted="1"&gt;&lt;dc:title&gt;Lossless_FFv1 Test&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/mp4:DLNA.ORG_OP=01" size="1000000" duration="0:00:07.000" resolution="1024x688" bitrate="52840240"&gt;`

[That part of the code](https://github.com/DigitalMediaServer/DigitalMediaServer/blob/9a7f23b600961ff8531d7edc87127f2851ad858c/src/main/java/net/pms/dlna/DLNAMediaInfo.java#L1990-L2002) is flawed, IMO.

As some renderers are more sensible to it because they have a bitrate limitation, as 25 Mb/s, it was more obvious to detect it with one of them.
I've fixed it with an ugly trick for a user, having AVI with rawvideo codec (from camera), but i'm sure a proper fix can and should be found. I just can't find one right now, so i'll appreciate any idea to get the real bitrate while transcoding, though i could not afford a big refactory myself if it need it.
I thought about using the below idea and divide that "more real" transcoded size by the total video duration.

- Concerning the size, that could give issue, such as videos without sound that are not played correctly while transcoded with `TranscodedVideoFileSize = 1000000` (and certainly others), i don't know if it will possible, but i thought about checking at the size of the first second transcoded (or the full 2.5 s that it buffer) (in the buffer ?) and multiply that by the total duration of the video. This value should be rounded up.
Do you think that it could be done ? or do you have a better idea ?

**EDIT**: `getRealVideoBitrate()` What a joke ;-)

**Comment by Nadahar** [comment]
@Sami32 I'm aware that there's a lot of stuff that's wrong/missing, including bitrates, sizes etc. My plan was to rewrite the whole thing from scratch, as I don't see much hope for "fixing" the code that's already there. So many wrong assumptions are made, but there's also a lack of available information.

I don't know a proper way to get the bitrate when transcoding, I don't know if one exists. Taking the first 2,5 seconds is likely to be very wrong, as many videos start with some kind of intro which probably has a lower bitrate than the rest. Also, we'd need to know the maximum bitrate, which isn't possible without probing the whole file. In addition, we need to know this long before playback is started, at the browsing stage. In short, it's not possible to get this information in time.

My plan is different; I'm planning to only transcode to defined DLNA profiles. The profiles have defined bitrate (and other) constraints, so my idea is to tell the transcoding engine to keep the bitrate withing the defined limit. As I understand the DLNA standard, the information in the DIDL should then be the defined maximum bitrate, not the actual bitrate.

As it is now, DLNA profiles aren't used (or, the little DLNA information sent is wrong). It's impossible to tell how it would work if implemented correctly as long as it is so much non-compliance, so I'm simply ignoring these problems until it is reimplemented.

**Comment by Sami32** [comment]
Surely the cleanest and best approach, that's an advantage to work without users :wink: 

Some users want play their "camera" AVI, so i don't really have choice for the quick fix...

**Comment by Sami32** [comment]
Following your post, i should add that you could be surprised by the future MediaInfo DLNA's profiles support :wink:

**Comment by Nadahar** [comment]
@Sami32 I really don't see how a quick fix could be done, as the information simply isn't there. The only thing I can think of is to make a "guesstimation" where you use the source codecs and their bitrates, resolution etc into account and then use some pre-defined conversion value between the different formats and apply that "guesstimate factor" to the source bitrate. It sounds like quite å project to me, but I guess something could be done, although that's the kind of solution one would end up having to adjust for eternity.

**Comment by Sami32** [comment]
I mean really quick :wink: 
Not one imperfect that will need eternal adjustement.

I just used the bandwidth limitation set inside the renderer configuration file because  thet are set their to follow the renderer specifications limiting the bitrate, but only for video having an original bitrate superior to 200 Mb/s, as all the renderers that i saw with limitation followed the same limitation, at least the far more popular one.

Still a more quick way is to hardcode the 25 MB/s bitrate value to be set in the DIDL while the original bitrate is superior to 200 Mb/s

**Comment by Nadahar** [comment]
@Sami32 I didn't quite understand that. When you say "superior" - do you mean greater than? In any case, I don't quite see the point of just trying to "cheat" the renderer. If the bitrate are greater than what the renderer can handle, I doubt playback will be very nice. Or, did I simply misunderstand you?

**Comment by Sami32** [comment]
Yes, i meant `>` ("supérieur" in french)

I was not clear, precise, so misunderstanding was easy. When i transcode with custom option in the renderer i made sure that the bitrate will be not more of 25 MB/s, but as the code is now, the bitrate set into the DIDL string will be totally wrong and more important, not supported by the renderer that freeze, as your with AAC having high bitrate.
So i just trick the bitrate value set into the DIDL string.
Do i was more clear this time :question:

**Comment by Nadahar** [comment]
@Sami32 
> Do i was more clear this time ❓

I guess you meant "Was I clearer this time?" If so, I guess somewhat but I still don't quite follow you. If a file is transcoded with a bitrate limitation (as a transcoder parameter), then I'd say it would be correct to use that bitrate limitation in the DIDL. The problem might be to know this when the DIDL is created, but if that is known that isn't really "tricking". The logic would have to make sure that the media would really be transcoded with that limit though. Is this what you're doing?

**Comment by Sami32** [comment]
Yes :smile:

**Comment by Sami32** [comment]
Yes :smile:

**Comment by Nadahar** [comment]
@Sami32 While we're at it, do you mean "less than" when you say "inferior" as well? Anterior is another word you use that I don't understand, is sounds like "older than" or "more ancient than" to me, but that often doesn't make sense in the way you use it.

**Comment by Sami32** [comment]
Sorry...i feel that it not clear as i would like but i miss the word and set what i think is the more near than french.
Yes, i use anterior, as "before", "less than"; "inférieur" or "moins que" in french, so "less than" is good for me to remember, thanks :wink:
