### ISSUE TITLE
Crash sometimes at scan start

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#44]
No error is found into the log.
I don't think that it is related but i've found that in medias.trace.db:
```
2018-05-13 23:26:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "FILES" not found; SQL statement:
SELECT count(*) FROM FILES [42102-196]
2018-05-13 23:26:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "FILES" not found; SQL statement:
DROP TABLE FILES [42102-196]
```

More informations will be added when i will able to reproduce it.
Possibly arise when few files are parsed and get fixed when more media folders are added to be parsed?

**Comment by Nadahar** [comment]
The above doesn't look like an error to me. It seems like a part of the database initialization where the database is checked and tables are deleted if the "version" is wrong.

How do you know that there's a crash if there's nothing in the log? Does it just quit without an error?

**Comment by Sami32** [comment]
Very simple, DMS close itself after scan is started.

**Comment by Nadahar** [comment]
See if there's any JNA error reports in the folder you started DMS from then. I can't think of a Java error that would make it just close without logging anything.

**Comment by Sami32** [comment]
I already posted you a private log on that matter some weeks ago.

**Comment by Sami32** [comment]
Hehe, and maybe you answered me that it was coming from MediaInfo but i cannot remember ;P

**Comment by Sami32** [comment]
Not sure that come from JNA or our implementation used for MediaInfo thought:
[hs_err_pid208.log](https://github.com/DigitalMediaServer/DigitalMediaServer/files/2002963/hs_err_pid208.log)
[hs_err_pid3736.log](https://github.com/DigitalMediaServer/DigitalMediaServer/files/2002964/hs_err_pid3736.log)
[hs_err_pid3760.log](https://github.com/DigitalMediaServer/DigitalMediaServer/files/2002965/hs_err_pid3760.log)

**Comment by Nadahar** [comment]
Those are what I call "JNA logs". Technically they are JVM crash logs, but the problem comes from a JNA call to MediaInfo:
```logtalk
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokeInt(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)I+0
j  com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;ZI)Ljava/lang/Object;+211
J 3043 C1 com.sun.jna.Function.invoke(Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object; (548 bytes) @ 0x00bdf7fe [0x00bdf1d0+0x62e]
j  com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+344
j  net.pms.dlna.$Proxy6.Open(Lcom/sun/jna/Pointer;Lcom/sun/jna/WString;)I+20
j  net.pms.dlna.MediaInfo.Open(Ljava/lang/String;)I+15
j  net.pms.dlna.LibMediaInfoParser.parse(Lnet/pms/dlna/DLNAMediaInfo;Lnet/pms/dlna/InputFile;ILnet/pms/configuration/RendererConfiguration;)V+59
j  net.pms.configuration.FormatConfiguration.parse(Lnet/pms/dlna/DLNAMediaInfo;Lnet/pms/dlna/InputFile;Lnet/pms/formats/Format;ILnet/pms/configuration/RendererConfiguration;)V+143
j  net.pms.formats.Format.parse(Lnet/pms/dlna/DLNAMediaInfo;Lnet/pms/dlna/InputFile;ILnet/pms/configuration/RendererConfiguration;)V+24
j  net.pms.dlna.RealFile.resolve()V+308
j  net.pms.dlna.DLNAResource.syncResolve()V+1
j  net.pms.dlna.DLNAResource.run()V+8
j  net.pms.dlna.RealFile.isValid()Z+134
j  net.pms.dlna.DLNAResource.addChild(Lnet/pms/dlna/DLNAResource;Z)V+195
j  net.pms.dlna.DLNAResource.addChild(Lnet/pms/dlna/DLNAResource;)V+3
j  net.pms.dlna.MapFile.manageFile(Ljava/io/File;)V+431
j  net.pms.dlna.MapFile.analyzeChildren(I)Z+172
j  net.pms.dlna.RootFolder.scan(Lnet/pms/dlna/DLNAResource;)V+175
j  net.pms.dlna.RootFolder.scan()V+59
j  net.pms.dlna.DLNAMediaDatabase.run()V+7
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
```
As you can see it happens during the call to the MediaInfo "Open" function. I can't tell what's causing it, but it's either a JNA problem or a compatibility problem with MediaInfo. Can you try to open the file that crashes in MediaInfo manually (with the same version of MediaInfo)?

**Comment by Sami32** [comment]
Did you see a file name somewhere?

**Comment by Nadahar** [comment]
Not in that log, but if you look in debug.log it should be either the last logged file or the next one (in the folder).

**Comment by Nadahar** [comment]
That sounds strange. I am unable to debug JNA/JNI errors anyway, I have no idea where to start - especially when I can't reproduce it. It's probably related either to your CPU or to XP.

**Comment by Sami32** [comment]
Yes, sorry, i get confuse after having read that thread:
http://www.universalmediaserver.com/forum/viewtopic.php?t=9976&start=10
What a fair guy...

**Comment by Nadahar** [comment]
Hehe, yes, nice guy. I don't think this is related to your error though, the only thing that is common is that it results in a JVM crash report.

**Comment by Sami32** [comment]
It seem related to MediaInfo JNA handling by our code.
[hs_err_pid3532.log](https://github.com/DigitalMediaServer/DigitalMediaServer/files/2199818/hs_err_pid3532.log)

**Comment by Nadahar** [comment]
How can you tell?

**Comment by Sami32** [comment]
It was one file that made MediaInfo file crash.
So lets hope that it will get fixed.

**Comment by Nadahar** [comment]
Great, I couldn't quite understand why you thought it was in our code :innocent:
