### ISSUE TITLE
Add a possibility to have more than 1 alternative subtitle folder.

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#56]
@madoka did suggested, requested that feature because he burn its movies and external subtitles on DVDs, but years later better ASS subtitles come and he put it on its hardrive, so he have to change the subtitles folder every time as he use external subtitles for every movie.

A such specific add should only be added in the DMS.conf to avoid to crowd more the GUI IMO.

**EDIT**:
If that can help, [here](https://github.com/ps3mediaserver/ps3mediaserver/commit/73b0e48443c7d310c3c70a24865a70b7dec6da23) is the original PR that have been slightly modified since that era.

**Comment by Nadahar** [comment]
This has all been completely rewritten in #34, so the old PR won't be of much use. I don't know if I understood the problem. The way it's supposed to work, he can just dump all the subtitles in the alternative folder, and they will be matched by file name.

It would be possible to add multiple "alternative" folders, but I'm afraid it will slow down the subtitles search.

**Comment by Sami32** [comment]
No you didn't. No way to add it to a burned DVD-R except to burn a new DVD...

**Comment by Sami32** [comment]
Solved
