### ISSUE TITLE
DVR-MS not tested and parsed correctly

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#6]
DVR-MS has been omitted from format tests and from LibMediaInfoParser

**Comment by Sami32** [comment]
That make me wondering if ffmpeg_MPGMUX.exe is still be need or not ?
Perhaps since the old era, FFmpeg is now able to handle it very well ?

**Comment by Nadahar** [comment]
@Sami32 That's exactly what I want to figure out. I discovered that there's a lot of bugs related to the use of ```ffmpeg_MPGMUX.exe```, so I need to figure out if it's needed so I have to try to fix it, or if it could just be removed.

From the little information I've found this far, it seems like nothing has happened in the FFmpeg parser related to that for years, so it's probably still needed. It's a special build with some "hacks" that fixes some timestamp issues on the fly that the recordings made by Windows is reportedly full off. That means, that the "normal" FFmpeg will probably be able to transcode files that's "perfect", but will struggle with typical non-perfect recordings.

Having only one sample file isn't ideal to determine this, but it's not very easy to find these files. Windows XP Media Center Edition can generate them, but from what I understand one needs a TV card to capture from. I'm not going to get a TV card just to generate some stupid dvr-ms files, so any help to figure this out is appreciated.

**Comment by Sami32** [comment]
Sorry to give you good new, but these issues has been fixed :wink: 
That where i take my sample from, so you've already the best sample for tests LOL

**Comment by Nadahar** [comment]
@Sami32 That's great, then I see no need to keep it around.

**Comment by Sami32** [comment]
We better test it before.
And that mean use a recent FFmpeg build as well, so solve the subtitles issue related to fontconfig.

**Comment by Sami32** [comment]
I just tested it now, transcoding it to H264 / AAC in MP4 container without any issue.

**Comment by Nadahar** [comment]
@Sami32 With the version we currently use?

**Comment by Sami32** [comment]
Of course not, i said recent !
I used the N-86504 version, one month old i think.
I also tested transcoding it to MPEG1 without any issue.

**Comment by Nadahar** [comment]
@Sami32 Is this still an issue?

**Comment by Sami32** [comment]
Yes it is.
As they are special ASF files it should be safer to parse and identify them as DVR-MS file for a more easy debugging IMO.

**Comment by Sami32** [comment]
It seem that i've a branch for that but i don't remember what i've already done.
