### ISSUE TITLE
Navigation/Share libraries flaw when using DMS as a service

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#77]
Only tested under Linux and VLC for now. It work correctly while using the GUI.

Whatever the user's folders are, it only show one DMS instance showing all the default folders with default settings and one other with "Recently played", also if none of these are enabled in the configuration and display as expected when using the GUI.

**Comment by Nadahar** [comment]
I can't reproduce this. I edited `/root/.config/DigitalMediaServer/DMS.conf` and started the daemon as root, and it showed the configured folder.

I don't know what user you ran the service as, but remember that by default DMS will use `.config` in the current users home folder. That might not be ideal for a daemon, in which case the daemon should start DMS with a specific profile set.

There is also the issue of which user the daemon should run as, and of course the permissions to the profile folder and media folders. This shows how to start a service as a specific user, although it's still not clear to me how permissions are handled: https://askubuntu.com/questions/676007/how-do-i-make-my-systemd-service-run-via-specific-user-and-start-on-boot

**Comment by Sami32** [comment]
That is probably the root of my misunderstanding.
