### ISSUE TITLE
Web interface overlay message issue

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#80]
The Web interface overlayed message doesn't appear at the right place.

When staying on the Restart server button then go to the Web interface button, and do it again and again, make all the messages overlay under the Restart server button.

**Comment by Nadahar** [comment]
I already answered this in #78. There's nothing we can do about it that I know of other than to redesign the GUI.

**Comment by Sami32** [comment]
Ok, sorry :/
I've forgot about that.

**Comment by Sami32** [comment]
Oh you mean your answer there, i did'nt saw it. My refresh time is too low ;)
