### ISSUE TITLE
Question and problems of GUI

### ISSUE THREAD

**Issue by onon765trb** [DigitalMediaServer/DigitalMediaServer#91]
I have found DMS. And I have built it.
Its UI is stylish and cool! Its behavior is light!
I become to like DMS.
Can I PR? though the PRs may include PRed to UMS.

Some problems I found
The belows are not displayed.
the explanation of wizard
confirm after change language
bitrate and channel of general tab of transcoding tab

**Comment by Nadahar** [comment]
Hi @onon765trb 

You are of course very welcome to make PRs here as well. It doesn't matter if the same code is submitted to UMS.

If some translations are missing for Japanese, you can submit them yourself [in our Crowdin project](https://crowdin.com/project/DigitalMediaServer). If you choose to do so, please send me a PM on Crowdin (I'm [Nadar](https://crowdin.com/profile/Nadar) at Crowdin), and I'll give you extended permissions so that you edit and approve/disapprove translations.

When it comes to the missing labels, this has already been fixed in #34. Since DMS is not yet ready for release, there are currently important fixes and changes that still exist in multiple branches that hasn't yet been merged into master.

**Comment by Nadahar** [comment]
You should know that my original goal when I created DMS was to have higher code quality (and in time fewer bugs) than UMS. You will therefore probably experience that you will face more questions about the code submitted than you do at UMS.

I hope you wan't be scared or offended by this, it's not meant as criticism or rejection, I simply have to make the questions necessary for me to properly understand the proposed changes. This is necessary to properly review the changes and how they will affect the code quality.

I know that @Sami32 finds my questions very frustrating at times, but we usually figure it out in the end :wink:

**Comment by onon765trb** [comment]
@Nadahar
Thank you for your words. I am happy!
My goal is that many people are enjoying media, Media environment is very various.
At least, same questions are repeated in Japanese bbs. 
To solve it, I think that good interface and higher customization are needed. The former is achieved by you.
Please understand it. And I am a super beginner of JAVA. Please don't forget it.

**Comment by Nadahar** [comment]
@onon765trb I completely agree with your goal. When I joined UMS in 2015 I had never seen a line of Java code before in my life, so I have full understanding for how it is being unfamiliar with it. The project is also quite large and not always very logical, so it can be very frustrating and difficult to get the overview. I know all about that too :wink: 

Rest assured, we try to help each other as best as we can, and to learn from each other. So, as long as your are willing to listen and learn, but also share your knowledge, we should all grow more skilled. While I probably know more Java than you do right now, I know that you know much more about FFmpeg than I do. If we all help each other, we will all grow.

So, don't be afraid to submit code, just try to take the discussion that might follow as an attempt to make it as good as possible, not as criticism.

**Comment by Sami32** [comment]
@onon765trb Hehe, yes i confirm, sometimes @Nadahar perfectionism can irritate, so in such case we need to remember that it is for the project benefice :smiley:

**Comment by onon765trb** [comment]
Thank you for your welcomes.
Now, I am rewriting my codes for DMS.

**Comment by Nadahar** [comment]
@onon765trb How and where you contribute is entirely up to you. You should know that you don't have to choose either UMS or DMS, there's nothing wrong with contributing both places if you so wish.

**Comment by SubJunk** [comment]
I agree, our code goes back and forth between projects and our developers collaborate so there is no need to choose from my perspective

**Comment by onon765trb** [comment]
Just I do not well know how to use github.

**Comment by Sami32** [comment]
@onon765trb We mostly use Tortoise Git now, but i began with Github and some with Eclipse but they are limited. So later i used the @Nadahar recommended Git Tortoise. 

I've no real experience of what should better for macOS but i post you some links in case you will interested later:
https://stackoverflow.com/questions/1440081/is-there-a-good-visual-git-tool-for-mac-os-x-or-windows
https://alternativeto.net/software/tortoisegit/?platform=mac

I hope that it could be of some help to you later.

**Comment by Nadahar** [comment]
@onon765trb I can't say for sure what's the "best" tools for macOS, but it looks to me like [GitX](https://github.com/gitx/gitx/releases) is a reasonably good tool.

I would also very much recommend to use Eclipse if you're not already using it. The last version of Eclipse that supports Java 7 is [Eclipse 4.5 (Mars)](http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-macosx-cocoa-x86_64.tar.gz). I'd recommend using a Java 7 capable version as long as we support Java 7 to avoid complications.

**Comment by SubJunk** [comment]
I can recommend SourceTree for macOS, I use it at work all day https://www.sourcetreeapp.com/
